### ISSUE TITLE
Automatically start WSA when its not running

### ISSUE THREAD

**Issue by zalnaRs** [Simizfo/WSATools#15]
Automatically start WSA when its not running instead of using continues mode.

**Comment by Simizfo** [comment]
Hi there.

Thanks for opening a ticket!
WSATools should already do that. Continuous mode is not required, but it works better in that case. 

Doesn't it work for you?

**Comment by Ceus** [comment]
I noticed that when not in continuous mode, it hangs with a message stating that it is connecting(?) I will have to try replicating this. It happened twice to me shortly after install, so I switched the subsystem to Continuous which seemed to resolve the issue right away. 

My computer isn't slow to start any of the subsystems, so I don't think it is related to how long it takes for the subsystem to initialize.

I will test and post my results.

**Comment by Ceus** [comment]
Alright. Here is a video of me double clicking on the Installer.apk which is a Harry Potter Puzzle game. The app opens and immediately closes. I did try to install the app once before this video, it loaded the app to the welcome screen and asked me to select an APK.

The recording is after the first attempt to install the APK by double clicking on the file, the app crashes and when I manually opened the app after it crashed, it started just fine. After, I closed the app, tested all over again and every instance seemed to work after. It seems to be intermittent, but seems to consistently work with the Continuous mode set.

[Video](https://www.screencast.com/t/HcIoCT9TvwRx)

I will post more if I find out anymore information.

**Comment by Simizfo** [comment]
Wow that's too much! I was saying in the previous post that you made a detailed issue post, but that's even more! Thank you.

Here I have no idea. I'll have to investigate more. The video helps me, there's a few things that I need to try. Will update here once I have something done. Thanks again!

**Comment by zalnaRs** [comment]
> Hi there.
> 
> Thanks for opening a ticket!
> WSATools should already do that. Continuous mode is not required, but it works better in that case. 
> 
> Doesn't it work for you?

Hi. No WSATools does not start WSA automatically for me.

**Comment by Ceus** [comment]
> > Hi there.
> > Thanks for opening a ticket!
> > WSATools should already do that. Continuous mode is not required, but it works better in that case.
> > Doesn't it work for you?
> 
> Hi. No WSATools does not start WSA automatically for me.

What happens when you open WSATools? Do you get any messages? Any crashing? Other things to check that might help, look at Event Viewer for logs regarding the Android Subsystem or WSATools. Likely under **Custom Views -> Administrative Events** and **Windows Logs -> Application**

These will better help in finding out what is causing the issue.

**Comment by Ceus** [comment]
@Simizfo I downloaded an APK and clicked Open from my browser. This caused the infinite loading screen. Here is a copy of the Event Logs and Diagnostic Reports (Diagnostic Data Viewer app) related to the crash:

```log
Faulting application name: WsaClient.exe, version: 1.8.32836.0, time stamp: 0x61d52393
Faulting module name: ucrtbase.dll, version: 10.0.22000.1, time stamp: 0x00e78ce9
Exception code: 0xc0000409
Fault offset: 0x000000000007dd7e
Faulting process id: 0xf3f0
Faulting application start time: 0x01d80777eff728bd
Faulting application path: C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_1.8.32836.0_x64__8wekyb3d8bbwe\WsaClient\WsaClient.exe
Faulting module path: C:\WINDOWS\System32\ucrtbase.dll
Report Id: 058d121f-9bad-4d66-af8b-09493bcacff2
Faulting package full name: MicrosoftCorporationII.WindowsSubsystemForAndroid_1.8.32836.0_x64__8wekyb3d8bbwe
Faulting package-relative application ID: App
```

```log
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user J-DESK\user SID (S-1-5-21-4221264291-1238005891-3829219879-1001) from address LocalHost (Using LRPC) running in the application container MicrosoftWindows.Client.WebExperience_421.20050.505.0_x64__cw5n1h2txyewy SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
```

```log
The application-specific permission settings do not grant Local Launch permission for the COM Server application with CLSID 
{286DD941-F692-41ED-A20D-8E8AA9181B10}
 and APPID 
Unavailable
 to the user J-DESK\user SID (S-1-5-21-4221264291-1238005891-3829219879-1001) from address LocalHost (Using LRPC) running in the application container MicrosoftCorporationII.WindowsSubsystemForAndroid_1.8.32836.0_x64__8wekyb3d8bbwe SID (S-1-15-2-4120862662-1149765626-4064695116-299589112-4208539117-2961988684-1460418210). This security permission can be modified using the Component Services administrative tool.
```

```log
Application: WSAToolsCore.exe
CoreCLR Version: 5.0.1221.52207
.NET Version: 5.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException: Could not load file or assembly 'System.IO.Compression.ZipFile, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'System.IO.Compression.ZipFile, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at WSAToolsCore.MainClass.ReadApkInfo()
   at WSAToolsCore.MainClass.Main(String[] args)
```

```log
Faulting application name: WSAToolsCore.exe, version: 1.0.0.0, time stamp: 0x61732c02
Faulting module name: KERNELBASE.dll, version: 10.0.22000.348, time stamp: 0x065c557a
Exception code: 0xe0434352
Fault offset: 0x000000000004478c
Faulting process id: 0xe4ec
Faulting application start time: 0x01d80779eb9671e3
Faulting application path: C:\Program Files\WindowsApps\54406Simizfo.WSATools_0.1.70.0_x64__f0x555vvp18ze\WSAToolsCore\WSAToolsCore.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 6a74a1aa-508a-46fd-a7e2-ad528fee4ede
Faulting package full name: 54406Simizfo.WSATools_0.1.70.0_x64__f0x555vvp18ze
Faulting package-relative application ID: App
```

```log
Application: WSAToolsCore.exe
CoreCLR Version: 5.0.1221.52207
.NET Version: 5.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.BadImageFormatException: Could not load file or assembly 'System.IO.Compression.ZipFile, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. Format of the executable (.exe) or library (.dll) is invalid.
File name: 'System.IO.Compression.ZipFile, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at WSAToolsCore.MainClass.ReadApkInfo()
   at WSAToolsCore.MainClass.Main(String[] args)
```

**Diagnostic Reports**
```log
Description
Faulting Application Path:	 C:\Program Files\WindowsApps\54406Simizfo.WSATools_0.1.70.0_x64__f0x555vvp18ze\WSAToolsCore\WSAToolsCore.exe
Creation Time:			 1/12/2022 12:02:03 AM
Problem:			 Stopped working
Status:				 Report sent

Problem signature
Problem Event Name:           MoAppCrash
Package Full Name:            54406Simizfo.WSATools_0.1.70.0_x64__f0x555vvp18ze
Application Name:             praid:App
Application Version:          1.0.0.0
Application Timestamp:        61732c02
Fault Module Name:            KERNELBASE.dll
Fault Module Version:         10.0.22000.348
Fault Module Timestamp:       065c557a
Exception Code:               e0434352
Exception Offset:             000000000004478c

Extra information about the problem
Bucket ID:			 17db6fb63ce4da7611de81bed5e14000 (1287609200106618880)
```

```log
Windows Subsystem for Android(TM)

Description
Faulting Application Path:	 C:\Program Files\WindowsApps\MicrosoftCorporationII.WindowsSubsystemForAndroid_1.8.32836.0_x64__8wekyb3d8bbwe\WsaClient\WsaClient.exe
Creation Time:			 1/11/2022 11:55:00 PM
Problem:			 Stopped working
Status:				 Report sent

Problem signature
Problem Event Name:           MoBEX
Package Full Name:            MicrosoftCorporationII.WindowsSubsystemForAndroid_1.8.32836.0_x64__8wekyb3d8bbwe
Application Name:             praid:App
Application Version:          1.8.32836.0
Application Timestamp:        61d52393
Fault Module Name:            ucrtbase.dll
Fault Module Version:         10.0.22000.1
Fault Module Timestamp:       00e78ce9
Exception Offset:             000000000007dd7e
Exception Code:               c0000409
Exception Data:               0000000000000007

Extra information about the problem
Bucket ID:			 f6ce0dbef9604a589b2eeb8c21e99ef4 (1958761875049651956)
```

**Comment by Simizfo** [comment]
Hmmmm, that's specific and definitely helps me! I guess I know what's happening. Thanks!
Moving this in a new issue, though, as it's not related to the original problem.

**Comment by Simizfo** [comment]
Closing this as it seems to be a single case. Please reopen this if it still happens.
